-- ═══════════════════════════════════════════════
-- 다른 앱 3개의 테이블도 같이 옮기기
-- ═══════════════════════════════════════════════
--
-- 같은 Supabase 프로젝트를 쓰는 앱이 더 있습니다.
--   버스킹 곡신청  → busking_submissions, busking_config
--   토요일 RSVP    → saturday_poll_config, saturday_poll_responses
--
-- 이 앱들도 새 프로젝트로 옮기려면,
--   1) 아래 [A] 를 새(서울) 프로젝트에서 실행해 테이블을 만들고
--   2) 아래 [B] 를 기존(뭄바이) 프로젝트에서 실행해 나온 INSERT 문을
--      새 프로젝트에 붙여넣어 실행하세요.
--   3) 각 앱의 코드에 적힌 Supabase 주소·키도 새 값으로 바꿔야 합니다.
--
-- ⚠️ 세 앱을 당분간 옮기지 않고 기존 프로젝트에 그대로 둬도 됩니다.
--    그 경우 허브만 새 프로젝트를 쓰고, 캐치마이크 대기열은
--    허브와 기존 앱이 서로 다른 곳을 보게 되니 주의하세요.
-- ═══════════════════════════════════════════════


-- ─────────────── [A] 새 프로젝트에서 실행 ───────────────

create table if not exists busking_submissions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text,
  song text,
  artist text,
  memo text,
  status text
);

create table if not exists busking_config (
  id int primary key default 1,
  deadline timestamptz,
  constraint busking_config_single_row check (id = 1)
);
insert into busking_config (id, deadline) values (1, null) on conflict (id) do nothing;

alter table busking_submissions enable row level security;
alter table busking_config enable row level security;

drop policy if exists "Allow public read" on busking_submissions;
drop policy if exists "Allow public insert" on busking_submissions;
drop policy if exists "Allow public update" on busking_submissions;
drop policy if exists "Allow public delete" on busking_submissions;
create policy "Allow public read"   on busking_submissions for select to anon using (true);
create policy "Allow public insert" on busking_submissions for insert to anon with check (true);
create policy "Allow public update" on busking_submissions for update to anon using (true) with check (true);
create policy "Allow public delete" on busking_submissions for delete to anon using (true);

drop policy if exists "Allow public read config" on busking_config;
drop policy if exists "Allow public insert config" on busking_config;
drop policy if exists "Allow public update config" on busking_config;
create policy "Allow public read config"   on busking_config for select to anon using (true);
create policy "Allow public insert config" on busking_config for insert to anon with check (true);
create policy "Allow public update config" on busking_config for update to anon using (true) with check (true);

-- ⚠️ saturday_poll_* 는 만들어진 구조를 제가 알 수 없습니다.
--    기존 프로젝트에서 아래를 실행해 구조를 확인한 뒤 옮겨주세요.
--
--    select column_name, data_type, is_nullable, column_default
--    from information_schema.columns
--    where table_name in ('saturday_poll_config','saturday_poll_responses')
--    order by table_name, ordinal_position;


-- ─────────── [B] 기존 프로젝트에서 실행 (데이터 뽑기) ───────────
/*
select 'insert into busking_submissions (id,created_at,name,song,artist,memo,status) values '
  || string_agg(format('(%L,%L,%L,%L,%L,%L,%L)', id, created_at, name, song, artist, memo, status), E',\n  ')
  || ' on conflict (id) do nothing;'
from busking_submissions
having count(*) > 0

union all

select 'update busking_config set deadline = ' || coalesce(format('%L', deadline), 'null') || ' where id = 1;'
from busking_config where id = 1;
*/
